---
- hosts: all
  gather_facts: yes
  become: true
  roles:
    - node-exporter

- hosts: slurm
  gather_facts: yes
  become: true
  roles:
    - ansible-role-slurm-exporter

- hosts: Login
  gather_facts: yes
  become: true

  vars:
    prometheus_slurm_exporter: "{{ groups['slurm_master'] | map('extract',hostvars,'ansible_nodename') | list }}"
    prometheus_target_nodes: "{{ groups['all'] | map('extract',hostvars,'ansible_nodename') | list }}"
    prometheus_scrape_configs:
      - job_name: "prometheus"    # Custom scrape job, here using `static_config`
        metrics_path: "/metrics"
        static_configs:
          - targets:
              - "127.0.0.1:9090"
      - job_name: 'slurm_exporter'
        scrape_interval:  30s
        scrape_timeout:   30s
        static_configs:
          - targets: "{{ slurm_exporter }}"
      - job_name: 'node'
        static_configs:
          - targets: "{{node_targets}}"

  pre_tasks:
    - name: Init a node target empty list
      set_fact:
        node_targets: []

    - name: Create node exporter targets from inventory
      set_fact:
        node_targets: "{{ node_targets }} + [ '{{item}}:9100' ]"
      with_items: "{{ prometheus_target_nodes | list }}"
  roles:
    - role: prometheus


- hosts: Login
  gather_facts: yes
  become: true

  vars:
    # grafana_cert_crt: "{{ vault_grafana_cert_crt }}"
    # grafana_cert_key: "{{ vault_grafana_cert_key }}"
    #grafana_cert_crt: "{{ vault_bareos_pacs_server_tls_cert }}"
    #grafana_cert_key: "{{ vault_bareos_pacs_server_tls_key }}"
    grafana_server:
      # protocol: https
      enforce_domain: false
      socket: ""
      #cert_file: "{{ grafana_cert_crt_file }}"
      #cert_key: "{{ grafana_cert_key_file }}"
      enable_gzip: false
      static_root_path: public
      router_logging: false

    grafana_security:
      admin_user: "admin"
      # TODO: vault password
      admin_password: "admin"

    grafana_datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: 'http://127.0.0.1:9090'
        basicAuth: false

    grafana_dashboards:
      # node exporter full
      - dashboard_id: 1860
        revision_id: 12
        datasource: prometheus
      # Prometheus Dashboard
      - dashboard_id: 3662
        revision_id: 2
        datasource: prometheus
      # Innodb metrics
      - dashboard_id: 7365
        revision_id: 1
        datasource: prometheus

  roles:
    - ansible-role-grafana
