---
- hosts: all
  become: True
  vars:
    packages:
    - curl
    - wget
    - git

  tasks:
  - name: Ensure a list of packages installed
    yum:
      name: "{{ packages }}"

#   roles:
#   - { role: geerlingguy.repo-epel }

- hosts: login
  gather_facts: True

  vars:
    nis_enabled: True
    nis_initialize: True
    nis_server: True
    nis_domain: "hpca4se"

#   roles:
#   - { role: cscfi.nis }
